import os
os.system("python ./bleu.py")
os.system("python ./couplet.py")
os.system("python ./iwslt.py")
os.system("python ./model.py")
os.system("python ./nmt.py")
os.system("python ./reader.py")
os.system("python ./seq2seq.py")
os.system("python ./server.py")
